name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
       conda create -q -y --name testenv python=3.8 cython numpy pytest psutil pip
       conda install -c conda-forge pip numpy scipy coverage scikit-learn!=0.19.0 matplotlib numba ffmpeg libsndfile pysoundfile coveralls
    - name: Test with pytest
      run: |
        conda install pytest
        python setup.py install
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -U pywinauto
        pip install -U Pillow
        pip install python-xlib codecov coverage
        sudo apt-get update
        sudo apt-get -y install at-spi2-core
        sudo apt-get install -qq qt58base;
        sudo apt-get -y install qt58declarative qt58tools
        sudo apt-get install xsel
        sudo apt-get install libgtk-3-dev libgtk2.0-dev
        sudo apt-get install -y python3-gi
        sudo apt-get install --reinstall libgl1-mesa-dev
        source /opt/qt58/bin/qt58-env.sh;
        coverage run -a --include=pywinauto/mouse.py pywinauto/unittests/test_mouse.py
        coverage run -a --include=pywinauto/linux/keyboard.py pywinauto/unittests/test_keyboard.py
        coverage run -a --include=pywinauto/linux/clipboard.py pywinauto/unittests/test_clipboard_linux.py
        coverage run -a --include=pywinauto/linux/application.py pywinauto/unittests/test_application_linux.py
        coverage run -a --source=pywinauto/linux,pywinauto/controls pywinauto/unittests/test_atspi_element_info.py
        coverage run -a --source=pywinauto/linux,pywinauto/controls pywinauto/unittests/test_atspi_wrapper.py
        coverage run -a --source=pywinauto/linux,pywinauto/controls pywinauto/unittests/test_atspi_controls.py
        
